version: '2'

services:
  app:
    container_name: sportube
    image: semestrovka-908
    build: ./
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sportube
    ports:
      - "2077:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    container_name: bd
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=keb5f$g7
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sportube