<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/style/navbar.css">
    <title>Document</title>
</head>
<body>
<ul>
    <li><a class="active" href="/profile">Profile</a></li>
    <li><a href="/userPlaylists">Playlists</a></li>
    <li><a href="/createPlaylist">Create playlist</a></li>
    <li><a href="/createVideo">Create video</a></li>
    <li><a href="/searchVideo">Search videos</a></li>
    <li><a href="/chatM">Chat</a></li>
    <li><a href="/logout">Logout</a></li>
</ul>
</body>
</html>